# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/my/SEAL/native/examples/gene_HEll

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/my/SEAL/native/examples/gene_HEll

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/my/SEAL/native/examples/gene_HEll/CMakeFiles /root/my/SEAL/native/examples/gene_HEll/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/my/SEAL/native/examples/gene_HEll/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gene_server

# Build rule for target.
gene_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gene_server
.PHONY : gene_server

# fast build rule for target.
gene_server/fast:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/build
.PHONY : gene_server/fast

#=============================================================================
# Target rules for targets named gene_client

# Build rule for target.
gene_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gene_client
.PHONY : gene_client

# fast build rule for target.
gene_client/fast:
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/build
.PHONY : gene_client/fast

client.o: client.cpp.o

.PHONY : client.o

# target to build an object file
client.cpp.o:
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/client.cpp.o
.PHONY : client.cpp.o

client.i: client.cpp.i

.PHONY : client.i

# target to preprocess a source file
client.cpp.i:
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/client.cpp.i
.PHONY : client.cpp.i

client.s: client.cpp.s

.PHONY : client.s

# target to generate assembly for a file
client.cpp.s:
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/client.cpp.s
.PHONY : client.cpp.s

evalution.o: evalution.cpp.o

.PHONY : evalution.o

# target to build an object file
evalution.cpp.o:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/evalution.cpp.o
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/evalution.cpp.o
.PHONY : evalution.cpp.o

evalution.i: evalution.cpp.i

.PHONY : evalution.i

# target to preprocess a source file
evalution.cpp.i:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/evalution.cpp.i
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/evalution.cpp.i
.PHONY : evalution.cpp.i

evalution.s: evalution.cpp.s

.PHONY : evalution.s

# target to generate assembly for a file
evalution.cpp.s:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/evalution.cpp.s
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/evalution.cpp.s
.PHONY : evalution.cpp.s

gene.o: gene.cpp.o

.PHONY : gene.o

# target to build an object file
gene.cpp.o:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/gene.cpp.o
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/gene.cpp.o
.PHONY : gene.cpp.o

gene.i: gene.cpp.i

.PHONY : gene.i

# target to preprocess a source file
gene.cpp.i:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/gene.cpp.i
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/gene.cpp.i
.PHONY : gene.cpp.i

gene.s: gene.cpp.s

.PHONY : gene.s

# target to generate assembly for a file
gene.cpp.s:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/gene.cpp.s
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/gene.cpp.s
.PHONY : gene.cpp.s

gene_random.o: gene_random.cpp.o

.PHONY : gene_random.o

# target to build an object file
gene_random.cpp.o:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/gene_random.cpp.o
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/gene_random.cpp.o
.PHONY : gene_random.cpp.o

gene_random.i: gene_random.cpp.i

.PHONY : gene_random.i

# target to preprocess a source file
gene_random.cpp.i:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/gene_random.cpp.i
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/gene_random.cpp.i
.PHONY : gene_random.cpp.i

gene_random.s: gene_random.cpp.s

.PHONY : gene_random.s

# target to generate assembly for a file
gene_random.cpp.s:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/gene_random.cpp.s
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/gene_random.cpp.s
.PHONY : gene_random.cpp.s

networking.o: networking.cpp.o

.PHONY : networking.o

# target to build an object file
networking.cpp.o:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/networking.cpp.o
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/networking.cpp.o
.PHONY : networking.cpp.o

networking.i: networking.cpp.i

.PHONY : networking.i

# target to preprocess a source file
networking.cpp.i:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/networking.cpp.i
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/networking.cpp.i
.PHONY : networking.cpp.i

networking.s: networking.cpp.s

.PHONY : networking.s

# target to generate assembly for a file
networking.cpp.s:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/networking.cpp.s
	$(MAKE) -f CMakeFiles/gene_client.dir/build.make CMakeFiles/gene_client.dir/networking.cpp.s
.PHONY : networking.cpp.s

server.o: server.cpp.o

.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i

.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s

.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) -f CMakeFiles/gene_server.dir/build.make CMakeFiles/gene_server.dir/server.cpp.s
.PHONY : server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... gene_server"
	@echo "... gene_client"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... evalution.o"
	@echo "... evalution.i"
	@echo "... evalution.s"
	@echo "... gene.o"
	@echo "... gene.i"
	@echo "... gene.s"
	@echo "... gene_random.o"
	@echo "... gene_random.i"
	@echo "... gene_random.s"
	@echo "... networking.o"
	@echo "... networking.i"
	@echo "... networking.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

